### ISSUE TITLE
Example of using a STUN/TURN server

### ISSUE THREAD

**Issue by wmfairuz** [legastero/jingle-interop-demos#15]
Hi,

Is it possible to have an example (or a hint) configuration on how to use stanza.io with a STUN/TURN server?

Thanks.

**Comment by fippo** [comment]
see https://github.com/otalk/jingle.js/blob/master/docs/Reference.md#jingleaddiceserverinfo for stanza.io/jingle.js

For prosody you also want to use https://github.com/otalk/mod_turncredentials
@legastero where is the xep-0215 implementation?

**Comment by fippo** [comment]
https://github.com/otalk/stanza.io/blob/master/docs/Reference.md#clientdiscovericeserverscb -- there it is.

**Comment by wmfairuz** [comment]
Ok, thanks a million @fippo
