### ISSUE TITLE
Getting transport info error

### ISSUE THREAD

**Issue by lego-sharat** [legastero/jingle-interop-demos#5]
I am trying to get the strophe-jingle demo working. I have set up the Bosh and XMPP server. I am getting transport info error wen I am trying to call another xmpp peer.

Console log:

sendIceCandidate: last candidate. strophejingle.bundle.js:1418
Have we encountered any srflx candidates? false strophejingle.bundle.js:1449
Have we encountered any relay candidates? false 
signallingstate  closed 
transport info error strophejingle.bundle.js:1407
(anonymous function) strophejingle.bundle.js:1407
(anonymous function) strophejingle.bundle.js:1
Strophe.Handler.run strophejingle.bundle.js:1
(anonymous function) strophejingle.bundle.js:1
Strophe.forEachChild strophejingle.bundle.js:1
Strophe.Connection._dataRecv strophejingle.bundle.js:1
Strophe.Connection._onRequestStateChange

**Comment by fippo** [comment]
This looks like you're trying to call a bare JID. You need to call a full JID including resource.

**Comment by lego-sharat** [comment]
I have tried calling with a jid including resource and it gives the same
error.

On Thu, Dec 5, 2013 at 12:07 AM, Philipp Hancke notifications@github.comwrote:

> This looks like you're trying to call a bare JID. You need to call a full
> JID including resource.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/legastero/jingle-interop-demos/issues/5#issuecomment-29831911
> .

## 

Regards

Sharat Chandra
Software Engineer
Samsung Research India - Bangalore

**Comment by fippo** [comment]
mh... can you provide full console logs from both sides (or a url where I can test) please? signallingstate closed typically means the remote side rejected the offer.
