### ISSUE TITLE
Create legastero.github.io

### ISSUE THREAD

**Issue by lloydwatkin** [legastero/jingle-interop-demos#9]
By creating yourself a set of pages here I'll be able to access the demos via: 

http://legastero.github.io/jingle-interop-demos

**Comment by legastero** [comment]
Right. The gh-pages is already set up (http://legastero.github.io/jingle-interop-demos/xmpp-ftw/ works, for example), we just need an index page to list them all.

**Comment by legastero** [comment]
And done. Thanks!
